In [5]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import joblib

In [8]:
# import processed data file

df = joblib.load('files/Preprocessed_zomato_dataset.csv')
df.head()

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES,DAYS_OPEN
0,Hitchki,1200,"Modern Indian,North Indian,Chinese,Momos,Birya...",bandra kurla complex,Casual Dining,12noon to 130am,Excellent,4.9,3529.0,Mon-Sun
1,Baba Falooda,400,"Desserts,Ice Cream,Beverages",mahim,Dessert Parlor,2pm to 1am,Very Good,4.4,1723.0,Mon-Sun
2,Chin Chin Chu,1800,"Asian,Chinese",juhu,Casual Dining,12noon to 1am,Very Good,4.2,337.0,Mon-Sun
3,Butterfly High,1000,Modern Indian,bandra kurla complex,Bar,12noon to 130am,Very Good,4.3,1200.0,Mon-Sun
4,BKC DIVE,1200,"North Indian,Chinese,Continental",bandra kurla complex,Bar,1130am to 1am,Very Good,4.4,5995.0,Mon-Sun

In [71]:
import plotly.express as px
import plotly.io as pio

pio.renderers.default = 'vscode'

In [73]:
# 1. How many restaurants in mumbai for each type of cuisine?

fig = px.histogram(df, x='CUSINE TYPE', color='CUSINE TYPE',
 title= 'No. of Restaurants by Cuisine Type',
 labels={'CUSINE TYPE':'Cuisine Type'})
fig.show()

In [35]:
# 2. percentage of restaurants by rating type

rating_df = df['RATING_TYPE'].value_counts().reset_index()
rating_df

  RATING_TYPE  count
0     Average   4990
1        Good   4266
2   Very Good   1149
3   Excellent     96
4        Poor     46

In [76]:
rating_percent = df["RATING_TYPE"].value_counts().reset_index()

rating_percent

  RATING_TYPE  count
0     Average   4990
1        Good   4266
2   Very Good   1149
3   Excellent     96
4        Poor     46

In [78]:
fig = px.pie(
    rating_percent,
    names="RATING_TYPE",
    values="count",
    color="RATING_TYPE",
    title="Percentage of Restaurants by Cuisine",
).update_traces(textposition= 'inside', textinfo = 'percent+label')

fig.show()

In [122]:
# 3. which are top high rated seafood restaurants in mumbai?

high_rated = df.sort_values(by="RATING", ascending=False)

top_seafood_restaurants = high_rated[
    high_rated["CUSINE_CATEGORY"].str.contains("seafood", case=False, na=False)
]
top_seafood_restaurants.head(10)

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES,DAYS_OPEN
7104,Thangabali,1000,"Seafood,South Indian,Mangalorean,Andhra,Kerala",khar,Bar,"12noon to 4pm,7pm to 3am",Excellent,4.7,564.0,Mon-Sun
13685,Maharashtra Lunch Home,600,"Maharashtrian,Malwani,Konkan,Seafood",kharghar,Casual Dining,"11am to 345pm,7pm to 1145pm",Excellent,4.6,209.0,Mon-Sun
76,Ceremonial Kitchen & Co,1000,"Seafood,Maharashtrian,North Indian,Chinese",ghodbunder road,Casual Dining,1130am to 1130pm,Excellent,4.6,350.0,Mon-Sun
3380,Peco Peco,700,"Chinese,Seafood,Asian",powai,none,"12noon to 330pm,7pm to 1230AM",Excellent,4.5,497.0,Mon-Sun
884,Rajmanya- Seafood family restaurant,800,"Maharashtrian,Konkan,Seafood",vashi,Casual Dining,11am to 11pm,Excellent,4.5,178.0,Mon-Sun
12433,Quarter Canteen,1100,"North Indian,Seafood,Chinese",bandra,Casual Dining,"12noon to 330pm,7pm to 1am",Excellent,4.5,573.0,Mon-Sun
902,The Harbour Bay - SeaFood Kitchen & Bar,2400,"Seafood,Beverages",bandra,Casual Dining,12noon to 1am,Excellent,4.5,100.0,Mon-Sun
9954,Pi Bar and Kitchen,1600,"Continental,European,Italian,Seafood,Pizza,Des...",andheri,Bar,"12noon to 6pm,7pm to 12midnight",Excellent,4.5,2068.0,Mon-Sun
199,Malhar Lunch Home,900,"North Indian,Seafood,Mughlai",mira road,Casual Dining,"1030am to 4pm,7pm to 1230AM",Very Good,4.4,1457.0,Mon-Sun
9785,Nawab-E-Dilli - Kitchen & Bar,700,"Thai,Biryani,Chinese,North Indian,Kebab,Seafood",andheri,Casual Dining,1130am to 4am,Very Good,4.4,537.0,Mon-Sun

In [103]:
# 4. which is the best food truck in mumbai?

best_foodtruck = df[df['CUSINE TYPE'] == 'Food Truck'].sort_values(by= 'RATING', ascending = False)
best_foodtruck.head(3)

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES,DAYS_OPEN
262,Dumpling Delights,200,Momos,matunga,Food Truck,430pm to 930pm,Very Good,4.3,212.0,Mon-Sun
1017,Street Food Co.,250,"Fast Food,Chinese",virar,Food Truck,6pm to 3am,Very Good,4.1,274.0,Mon-Sun
8188,Indigo Burger Project- Bar Bank,500,"Burger,Sandwich,Beverages",juhu,Food Truck,12noon to 1am,Good,3.9,39.0,Mon-Sun

In [123]:
# Q5) Which places have the highest rated restaurant for each Cuisine Type in Mumbai?

fig = px.histogram(
    high_rated,
    x="REGION",
    y="RATING",
    color="CUSINE TYPE",
    title="High rated restaurant for each cuisine type",
).update_xaxes(categoryorder="total descending")
fig.show()

In [124]:
# Q6) What is the Avg Price Distibution of highest rated restaurant for each Cuisine Type in Mumbai?

avg_price = (
    high_rated.groupby(by=["REGION", "CUSINE TYPE"])["PRICE"].mean().reset_index()
)

avg_price

        REGION     CUSINE TYPE        PRICE
0     andheri           Bakery   361.111111
1     andheri              Bar  1560.000000
2     andheri    Beverage Shop   228.571429
3     andheri             Café   672.580645
4     andheri    Casual Dining   876.923077
..         ...             ...          ...
884      worli   Casual Dining   656.060606
885      worli  Dessert Parlor   200.000000
886      worli     Quick Bites   381.578947
887      worli      Sweet Shop   200.000000
888      worli            none   439.285714

[889 rows x 3 columns]

In [125]:
px.scatter(
    avg_price,
    x="REGION",
    y="PRICE",
    color='CUSINE TYPE',
    title="Avg price distrubition for each cuisine type",
    symbol="CUSINE TYPE",
).update_traces(marker_size=10).show()

In [132]:
# Q7) Which areas have a large number of Chinese Restaurant Market?

chinese_df = df[df['CUSINE_CATEGORY'].str.contains('Chinese')]
chinese_df.head(5)

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES,DAYS_OPEN
0,Hitchki,1200,"Modern Indian,North Indian,Chinese,Momos,Birya...",bandra kurla complex,Casual Dining,12noon to 130am,Excellent,4.9,3529.0,Mon-Sun
2,Chin Chin Chu,1800,"Asian,Chinese",juhu,Casual Dining,12noon to 1am,Very Good,4.2,337.0,Mon-Sun
4,BKC DIVE,1200,"North Indian,Chinese,Continental",bandra kurla complex,Bar,1130am to 1am,Very Good,4.4,5995.0,Mon-Sun
5,Flea Bazaar Café,800,"American,Asian,Street Food,North Indian,Luckno...",flea bazaar café,Café,12noon to 1am,Very Good,4.2,2042.0,Mon-Sun
6,Persian Darbar,1300,"Biryani,North Indian,Chinese,Mughlai",marol,Casual Dining,10am to 3am,Excellent,4.5,3058.0,Mon-Sun

In [134]:
px.histogram(chinese_df, x="REGION", title="Areas with large chinese market", color="REGION").show()

In [138]:
# Q8) Is there a relation between Price and Rating by each Cuisine Type?

relation = df.groupby(['CUSINE TYPE', 'RATING'])['PRICE'].mean().reset_index()
relation

    CUSINE TYPE  RATING       PRICE
0        Bakery     2.7  400.000000
1        Bakery     2.8  285.714286
2        Bakery     2.9  328.571429
3        Bakery     3.0  300.000000
4        Bakery     3.1  369.117647
..          ...     ...         ...
278        none     4.3  683.333333
279        none     4.4  555.000000
280        none     4.5  420.000000
281        none     4.6  687.500000
282        none     4.7  350.000000

[283 rows x 3 columns]

In [145]:
px.line(relation, y="PRICE", x="RATING",color='CUSINE TYPE').show()

In [155]:
# Q9) Is there a relation between Region and Price?


fig = px.scatter(
    df.groupby(["REGION"])["PRICE"].mean().reset_index(),
    x="REGION",
    y="PRICE",
    height=700
).update_traces(marker_size=8)
fig.update_yaxes(range=[0, 2000])
fig.show()

In [172]:
# Q10) Find the list of Affordable Restaurants?

# criteria => low price and high rated restaurant
# we'll calculate the economical price (i.e.. less than1/4th of expensive price).

aff_price = df["PRICE"].max() / 4

aff_res = high_rated[high_rated["PRICE"] <= aff_price]
print("total affordable restaurants: ", aff_res["NAME"].count())

aff_res.sort_values(by=["RATING", "PRICE"], ascending=[False, True]).head(5)

total affordable restaurants:  10190

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES,DAYS_OPEN
0,Hitchki,1200,"Modern Indian,North Indian,Chinese,Momos,Birya...",bandra kurla complex,Casual Dining,12noon to 130am,Excellent,4.9,3529.0,Mon-Sun
15007,Dessertino,300,"Desserts,Ice Cream",kandivali,Dessert Parlor,11am to 12midnight,Excellent,4.8,184.0,Mon-Sun
149,The Northern Vibe,300,"Momos,Rolls,Fast Food",powai,Quick Bites,12noon to 1130pm,Excellent,4.8,145.0,"Mon-Thu,12noon to 12midnight..."
66,Downtown China,750,"Chinese,Thai",andheri,Casual Dining,12noon to 12midnight,Excellent,4.8,162.0,Mon-Sun
9778,Rajdhani,950,"Gujarati,Rajasthani,North Indian",ghatkopar,Casual Dining,"12noon to 330pm,7pm to 11pm",Excellent,4.8,1451.0,Mon-Sun

In [176]:
# logic gap from the below restaurants
# 'Hitchki' has price 1200 and rating 4.9
# but 'Dessertino' has rating of 4.8 and price of 300
# comparing both, 'dessertino' is more affordable and high rated
# the same with the 'The Northern Vibe
#
# To Solve this
#   1. Normalize first
#   2. Include weights for rating and price.

# Normalization
aff_res["rating_norm"] = aff_res["RATING"] / aff_res["RATING"].max()
aff_res["price_norm"] = aff_res["PRICE"] / aff_res["PRICE"].max()

# adding weights (70% to rating and 30% to price)
# dividing by 1000 because rating scale is 0-5 but price is 0-5000.
aff_res["score"] = (0.7 * aff_res["rating_norm"]) + (0.3 * (1- aff_res["price_norm"]))

aff_res.sort_values(by="score", ascending=False)

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES,DAYS_OPEN,score,rating_norm,price_norm
1502,Cake Centre-The Dessert Maker,150,Desserts,mohammad ali road,Dessert Parlor,11am to 12midnight,Excellent,4.6,105.0,Mon-Sun,0.921143,0.938776,0.12
149,The Northern Vibe,300,"Momos,Rolls,Fast Food",powai,Quick Bites,12noon to 1130pm,Excellent,4.8,145.0,"Mon-Thu,12noon to 12midnight...",0.913714,0.979592,0.24
15007,Dessertino,300,"Desserts,Ice Cream",kandivali,Dessert Parlor,11am to 12midnight,Excellent,4.8,184.0,Mon-Sun,0.913714,0.979592,0.24
270,Ashok Vada Pav Stall,100,Street Food,prabhadevi,Quick Bites,11am to 930pm,Very Good,4.4,915.0,"Mon-Sat,Closed(Sun",0.904571,0.897959,0.08
14234,Cone Culture,250,European,kharghar,Casual Dining,Closed,Excellent,4.6,492.0,"Mon,12noon to 11pm(Tue-Sun",0.897143,0.938776,0.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7577,Sunny Da Dhaba,750,"North Indian,Chinese",mulund,Casual Dining,11am to 1am,Poor,2.1,129.0,Mon-Sun,0.420000,0.428571,0.60
7586,Sunny Da Dhaba,750,"Chinese,North Indian,Biryani",mulund,Casual Dining,11am to 1am,Poor,2.1,129.0,Mon-Sun,0.420000,0.428571,0.60
7516,Aangan Family Garden Restaurant,1200,"North Indian,Chinese,Continental",new panvel,Casual Dining,1130am to 1130pm,Average,2.8,53.0,Mon-Sun,0.412000,0.571429,0.96
672,Hotel Praveen International,1200,"North Indian,Chinese",ulhasnagar,Casual Dining,11pm to 1230AM,Average,2.8,18.0,Mon-Sun,0.412000,0.571429,0.96
7466,Salute,1000,"Chinese,North Indian",borivali,Casual Dining,"12noon to 3pm,7pm to 12midnight",Poor,2.3,229.0,Mon-Sun,0.388571,0.469388,0.80

In [ ]:
# Q10) Find the list of most Reliable Restaurants?
# The criteria for most Reliable Restaurants would be:-
# 1) Low Price 2) High Rated 3) Large No. of Votes

mean_votes = df['VOTES'].mean()

# Finding list of restaurants that have Votes greater than and equal to Mean of Vote
mean_rest_df = df[['NAME', 'PRICE', 'CUSINE_CATEGORY', 'REGION', 'CUSINE TYPE', 'VOTES']]
mean_rest_df = mean_rest_df[mean_rest_df['VOTES'] > int(mean_votes)]
mean_rest_df.sort_values(by='VOTES', inplace=True)
mean_rest_df

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,VOTES
99,Appetite - Resto Bar,700,"North Indian,Chinese",powai,Casual Dining,178.0
12267,Buddha Bowl,1000,"Asian,Healthy Food",bandra,none,178.0
2193,Mumbai Darbar,850,"North Indian,Chinese,Seafood",lower parel,Casual Dining,178.0
11211,Soul Curry,800,"Chinese,North Indian,Malwani,Mughlai,Biryani",bhandup,Casual Dining,178.0
2392,Jain Sweet & Farsan House,200,"Street Food,Beverages,Fast Food,Mithai",goregaon,Quick Bites,178.0
...,...,...,...,...,...,...
8539,Leopold Cafe & Bar,1600,"American,Chinese,Mughlai,Italian",colaba,Casual Dining,7327.0
1251,Joey's Pizza,800,Pizza,malad,Quick Bites,7350.0
5337,Chili's American Grill & Bar,1400,"American,Mexican,Burger,Tex-Mex",powai,Casual Dining,7377.0
3751,Prithvi Cafe,700,"Cafe,Fast Food",juhu,Café,8000.0
8897,Candies,700,"Cafe,Italian,North Indian,Desserts",bandra,Café,10217.0

In [178]:
reliable_rest_df = pd.merge(
    mean_rest_df, high_rated, how="inner", on=["NAME", "REGION"]
)
reliable_rest_df = reliable_rest_df[
    ["NAME", "PRICE_x", "CUSINE_CATEGORY_x", "REGION", "CUSINE TYPE_x"]
]
reliable_rest_df.rename(
    columns={
        "NAME": "NAME",
        "PRICE_x": "PRICE",
        "CUSINE_CATEGORY_x": "CUSINE_CATEGORY",
        "REGION": "REGION",
        "CUSINE TYPE_x": "CUSINE TYPE",
    },
    inplace=True,
)
reliable_rest_df

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE
0,Appetite - Resto Bar,700,"North Indian,Chinese",powai,Casual Dining
1,Buddha Bowl,1000,"Asian,Healthy Food",bandra,none
2,Mumbai Darbar,850,"North Indian,Chinese,Seafood",lower parel,Casual Dining
3,Soul Curry,800,"Chinese,North Indian,Malwani,Mughlai,Biryani",bhandup,Casual Dining
4,Jain Sweet & Farsan House,200,"Street Food,Beverages,Fast Food,Mithai",goregaon,Quick Bites
...,...,...,...,...,...
2358,Leopold Cafe & Bar,1600,"American,Chinese,Mughlai,Italian",colaba,Casual Dining
2359,Joey's Pizza,800,Pizza,malad,Quick Bites
2360,Chili's American Grill & Bar,1400,"American,Mexican,Burger,Tex-Mex",powai,Casual Dining
2361,Prithvi Cafe,700,"Cafe,Fast Food",juhu,Café
2362,Candies,700,"Cafe,Italian,North Indian,Desserts",bandra,Café